version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/react-aws
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: ./start_server.sh
      timeout: 300
      runas: root
