version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 545009853444.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t my-app .
      - docker tag my-app:latest 545009853444.dkr.ecr.us-east-1.amazonaws.com/my-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 545009853444.dkr.ecr.us-east-1.amazonaws.com/my-app:latest
artifacts:
  files: []
